# 🎬 Movies Data Analysis

### 📌 Project Overview
This project focuses on cleaning, transforming, and analyzing a Telugu movies dataset to extract meaningful insights using Python, SQL, and data visualization tools.

### 🎯 Objectives
- Perform data cleaning and preprocessing
- Handle missing values and inconsistencies
- Engineer useful features for analysis
- Prepare dataset for SQL and dashboarding
- Generate insights on movie trends, ratings, and popularity

## Importing Required Libraries and Load the Raw Dataset

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv('/telugumovies_dataset_raw.csv')
data.head(5)

,ID,Movie,Year,Certificate,Genre,Overview,Runtime,Rating,No.of.Ratings
0,0,Bahubali: The Beginning,2015.0,UA,"Action, Drama","In ancient India, an adventurous and darin...",159,8.1,99114
1,1,Baahubali 2: The Conclusion,2017.0,UA,"Action, Drama","When Shiva, the son of Bahubali, learns ab...",167,8.2,71458
2,2,1 - Nenokkadine,2014.0,UA,"Action, Thriller",A rock star must overcome his psychologica...,170,8.1,42372
3,3,Dhoom:3,2013.0,UA,"Action, Thriller","When Sahir, a circus entertainer trained i...",172,5.4,42112
4,4,Ra.One,2011.0,U,"Action, Adventure, Sci-Fi",When the titular antagonist of an action g...,156,4.6,37211

## Initial Data Exploration

In [6]:
data.describe()

              ID         Year      Runtime       Rating  No.of.Ratings
count  1400.0000  1352.000000  1400.000000  1400.000000    1400.000000
mean    699.5000  2005.013314   121.764286     6.317214    1214.755714
std     404.2895    13.148859    55.925792     1.314660    4328.073152
min       0.0000  1932.000000     0.000000     1.000000      49.000000
25%     349.7500  1997.000000   123.000000     5.500000      92.000000
50%     699.5000  2009.000000   141.000000     6.500000     255.500000
75%    1049.2500  2015.000000   154.000000     7.300000     829.000000
max    1399.0000  2020.000000   300.000000     9.500000   99114.000000

In [7]:
data.shape

(1400, 9)

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ID             1400 non-null   int64
 1   Movie          1400 non-null   object
 2   Year           1352 non-null   float64
 3   Certificate    951 non-null    object
 4   Genre          1389 non-null   object
 5   Overview       1221 non-null   object
 6   Runtime        1400 non-null   int64
 7   Rating         1400 non-null   float64
 8   No.of.Ratings  1400 non-null   int64
dtypes: float64(2), int64(3), object(4)
memory usage: 98.6+ KB

## Handling Missing Values

In [9]:
data.isnull().sum()

ID                 0
Movie              0
Year              48
Certificate      449
Genre             11
Overview         179
Runtime            0
Rating             0
No.of.Ratings      0
dtype: int64

In [10]:
data['Year'] = data['Year'].fillna(data['Year'].median())
data['Certificate'] = data['Certificate'].fillna('Unknown')
data['Genre'] = data['Genre'].fillna('Unknown')
data['Overview'] = data['Overview'].fillna('No overview available')
data['Runtime'] = data['Runtime'].replace(0, np.nan)
data['Runtime'] = data['Runtime'].fillna(data['Runtime'].median()).astype(int)

In [11]:
data.isnull().sum()

ID               0
Movie            0
Year             0
Certificate      0
Genre            0
Overview         0
Runtime          0
Rating           0
No.of.Ratings    0
dtype: int64


Handling Duplicate Values

In [12]:
data.duplicated().sum()

np.int64(0)

## Fixing Data Types and Columns

In [13]:
print(data.dtypes)

ID                 int64
Movie             object
Year             float64
Certificate       object
Genre             object
Overview          object
Runtime            int64
Rating           float64
No.of.Ratings      int64
dtype: object

In [14]:
data['Year'] = data['Year'].astype(int)
data.rename(columns={'No.of.Ratings': 'Num_Ratings'}, inplace=True)

In [15]:
print(data.dtypes)

ID               int64
Movie           object
Year             int64
Certificate     object
Genre           object
Overview        object
Runtime          int64
Rating         float64
Num_Ratings      int64
dtype: object

## Feature Engineering

In [16]:
#Created a Decade column to analyze trends over time.

data['Decade'] = (data['Year'] // 10) * 10

In [17]:
#Calculated movie age based on release year.
data['Movie_Age'] = 2026 - data['Year']

In [18]:
#log(1+x) is used because to not make score larger as the num_ratings range from 49 to 99999
data['Popularity_Score'] = data['Rating'] * np.log1p(data['Num_Ratings'])

In [19]:
#Extracted the first genre from multi-genre entries to simplify analysis and grouping.

data['Primary_Genre'] = data['Genre'].apply(lambda x: x.split(',')[0].strip())
data.head(5)

,ID,Movie,Year,Certificate,Genre,Overview,Runtime,Rating,Num_Ratings,Decade,Movie_Age,Popularity_Score,Primary_Genre
0,0,Bahubali: The Beginning,2015,UA,"Action, Drama","In ancient India, an adventurous and darin...",159,8.1,99114,2010,11,93.182692,Action
1,1,Baahubali 2: The Conclusion,2017,UA,"Action, Drama","When Shiva, the son of Bahubali, learns ab...",167,8.2,71458,2010,9,91.650409,Action
2,2,1 - Nenokkadine,2014,UA,"Action, Thriller",A rock star must overcome his psychologica...,170,8.1,42372,2010,12,86.299560,Action
3,3,Dhoom:3,2013,UA,"Action, Thriller","When Sahir, a circus entertainer trained i...",172,5.4,42112,2010,13,57.499804,Action
4,4,Ra.One,2011,U,"Action, Adventure, Sci-Fi",When the titular antagonist of an action g...,156,4.6,37211,2010,15,48.412178,Action

## Final Cleaned Dataset Overview

In [20]:
data.describe()

,ID,Year,Runtime,Rating,Num_Ratings,Decade,Movie_Age,Popularity_Score
count,1400.0000,1400.000000,1400.000000,1400.000000,1400.000000,1400.000000,1400.000000,1400.000000
mean,699.5000,2005.150000,144.860714,6.317214,1214.755714,2000.050000,20.850000,36.776023
std,404.2895,12.941682,17.792784,1.314660,4328.073152,12.768811,12.941682,13.054514
min,0.0000,1932.000000,60.000000,1.000000,49.000000,1930.000000,6.000000,4.672829
25%,349.7500,1998.000000,137.000000,5.500000,92.000000,1990.000000,11.000000,27.849029
50%,699.5000,2009.000000,145.000000,6.500000,255.500000,2000.000000,17.000000,34.195626
75%,1049.2500,2015.000000,154.000000,7.300000,829.000000,2010.000000,28.000000,43.376544
max,1399.0000,2020.000000,300.000000,9.500000,99114.000000,2020.000000,94.000000,93.182692

In [22]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1400 entries, 0 to 1399
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   ID                1400 non-null   int64
 1   Movie             1400 non-null   object
 2   Year              1400 non-null   int64
 3   Certificate       1400 non-null   object
 4   Genre             1400 non-null   object
 5   Overview          1400 non-null   object
 6   Runtime           1400 non-null   int64
 7   Rating            1400 non-null   float64
 8   Num_Ratings       1400 non-null   int64
 9   Decade            1400 non-null   int64
 10  Movie_Age         1400 non-null   int64
 11  Popularity_Score  1400 non-null   float64
 12  Primary_Genre     1400 non-null   object
dtypes: float64(2), int64(6), object(5)
memory usage: 142.3+ KB

In [21]:
data.to_csv("telugu_movies_cleaned.csv", index=False)